select PRODUCT_ID, PRODUCT_NAME, sum(AMOUNT) * PRICE as TOTAL_SALES
from FOOD_PRODUCT
join FOOD_ORDER
    using(PRODUCT_ID)
where PRODUCE_DATE like "2022-05%"
group by PRODUCT_ID
order by TOTAL_SALES desc, PRODUCT_ID asc