SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") as "DATE_OF_BIRTH"
FROM MEMBER_PROFILE
WHERE GENDER = 'W' and TLNO is not null and DATE_FORMAT(DATE_OF_BIRTH, "%m") = "03"
order by MEMBER_ID asc